service:
  name: nest-serverless-lambda-demo

plugins:
  - 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  # stage: ${opt:stage, 'dev'}
  # apiGateway:
  #   shouldStartNameWithService: true
  # environment:
  #   NODE_ENV: ${env:NODE_ENV}

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
